#!/usr/bin/python
import argparse
import os
def tody_bt(input, output):
    data = open(input, "r")
    out = open(output, "w")
    Regions = {}
    for line in data:
        line = line.strip()
        lines = line.split("\t")
        Chr, Start, End, new= lines[:4]
        region = (Chr, Start, End)
        if region in Regions:
            n=n+1
            Regions[region] = n
        elif region not in Regions and new == ".":
            Regions[region] =0
        else:
            n=1
            Regions[region] = n
    for key, val in Regions.items():
        key1="\t".join(key)
        out.write(key1+"\t"+str(val)+"\n")

path="/Users/yaminzhang/Desktop/lrs-de_novo/analysis_2022/tolerance"
os.chdir(path)
#tody_bt("sv_flt3_cdts_overlap_bt","sv_flt3_cdts_overlap_organise")


def main():
    parser = argparse.ArgumentParser(description="")
    parser.add_argument("-i", "--input", help="The input file that generated by bedtools.")
    parser.add_argument("-o", "--output", help="The name of output file.")
    args = parser.parse_args()
    tody_bt(args.input, args.output)

if __name__ == "__main__":
    main()
